// GENERAT AUTOMÀTICAMENT des de docs/diccionari — no editar a mà.
// Torna a generar-ho amb: npm run dades:genera

import type { EixTemperament } from '@vincle/shared-types';

export interface AssignacioTerme {
  readonly eix: EixTemperament;
  readonly puntuacio: number;
}

/** Termes de `temperament` → eixos puntuats. Font: docs/diccionari/termes-temperament.csv */
export const DICCIONARI: Readonly<Record<string, readonly AssignacioTerme[]>> = {
  "intelligent": [{ eix: "entrenabilitat", puntuacio: 7 }],
  "loyal": [{ eix: "orientacio-persona", puntuacio: 7 }],
  "alert": [{ eix: "alerta", puntuacio: 9 }],
  "energetic": [{ eix: "energia", puntuacio: 9 }],
  "courageous": [{ eix: "tolerancia-entorns", puntuacio: 8 }],
  "independent": [{ eix: "orientacio-persona", puntuacio: 4 }, { eix: "entrenabilitat", puntuacio: 3 }],
  "affectionate": [{ eix: "sociabilitat", puntuacio: 8 }],
  "friendly": [{ eix: "sociabilitat", puntuacio: 9 }],
  "protective": [{ eix: "orientacio-persona", puntuacio: 7 }],
  "playful": [{ eix: "energia", puntuacio: 8 }],
  "confident": [{ eix: "tolerancia-entorns", puntuacio: 9 }],
  "gentle": [{ eix: "sociabilitat", puntuacio: 6 }],
  "calm": [{ eix: "calma", puntuacio: 9 }],
  "work-focused": [{ eix: "entrenabilitat", puntuacio: 9 }],
  "devoted": [{ eix: "orientacio-persona", puntuacio: 6 }],
  "adaptable": [{ eix: "tolerancia-entorns", puntuacio: 9 }],
  "outgoing": [{ eix: "sociabilitat", puntuacio: 9 }],
  "eager to please": [{ eix: "entrenabilitat", puntuacio: 10 }],
  "athletic": [{ eix: "energia", puntuacio: 8 }],
  "docile": [{ eix: "calma", puntuacio: 6 }],
  "happy": [{ eix: "sociabilitat", puntuacio: 5 }],
  "reserved": [{ eix: "sociabilitat", puntuacio: 2 }],
  "lively": [{ eix: "calma", puntuacio: 3 }],
  "curious": [{ eix: "tolerancia-entorns", puntuacio: 7 }],
  "hardy": [{ eix: "tolerancia-entorns", puntuacio: 6 }],
  "spirited": [{ eix: "calma", puntuacio: 3 }],
  "dignified": [{ eix: "calma", puntuacio: 6 }],
  "smart": [{ eix: "entrenabilitat", puntuacio: 7 }],
  "aloof": [{ eix: "orientacio-persona", puntuacio: 2 }],
  "patient": [{ eix: "calma", puntuacio: 9 }],
  "agile": [{ eix: "energia", puntuacio: 6 }],
  "charming": [{ eix: "orientacio-persona", puntuacio: 8 }],
  "determined": [{ eix: "alerta", puntuacio: 5 }],
  "even-tempered": [{ eix: "calma", puntuacio: 5 }],
  "fearless": [{ eix: "tolerancia-entorns", puntuacio: 8 }],
  "mischievous": [{ eix: "entrenabilitat", puntuacio: 3 }],
  "active": [{ eix: "energia", puntuacio: 8 }],
  "amiable": [{ eix: "sociabilitat", puntuacio: 9 }],
  "cautious": [{ eix: "tolerancia-entorns", puntuacio: 3 }],
  "cheerful": [{ eix: "sociabilitat", puntuacio: 7 }],
  "clever": [{ eix: "entrenabilitat", puntuacio: 7 }],
  "easygoing": [{ eix: "calma", puntuacio: 8 }],
  "good-natured": [{ eix: "sociabilitat", puntuacio: 7 }],
  "merry": [{ eix: "sociabilitat", puntuacio: 6 }],
  "optimistic": [{ eix: "tolerancia-entorns", puntuacio: 6 }],
  "sensitive": [{ eix: "sociabilitat", puntuacio: 7 }],
  "sweet-tempered": [{ eix: "sociabilitat", puntuacio: 7 }],
  "tenacious": [{ eix: "alerta", puntuacio: 6 }],
};

/** Traduccions al català dels termes, per mostrar-los a la interfície (§5.2.1). */
export const TRADUCCIO_TERME: Readonly<Record<string, string>> = {
  "intelligent": "intel·ligent",
  "loyal": "lleial",
  "alert": "vigilant",
  "energetic": "enèrgic",
  "courageous": "valent",
  "independent": "independent",
  "affectionate": "afectuós",
  "friendly": "amigable",
  "protective": "protector",
  "playful": "juganer",
  "confident": "segur de si mateix",
  "gentle": "dolç",
  "calm": "tranquil",
  "work-focused": "orientat a la feina",
  "devoted": "entregat",
  "adaptable": "adaptable",
  "outgoing": "extravertit",
  "eager to please": "disposat a complaure",
  "athletic": "atlètic",
  "docile": "dòcil",
  "happy": "alegre",
  "reserved": "reservat",
  "lively": "vivaç",
  "curious": "curiós",
  "hardy": "resistent",
  "spirited": "animós",
  "dignified": "digne",
  "smart": "llest",
  "aloof": "distant",
  "patient": "pacient",
  "agile": "àgil",
  "charming": "encantador",
  "determined": "decidit",
  "even-tempered": "equilibrat",
  "fearless": "intrèpid",
  "mischievous": "entremaliat",
  "active": "actiu",
  "amiable": "afable",
  "cautious": "prudent",
  "cheerful": "jovial",
  "clever": "espavilat",
  "easygoing": "de tracte fàcil",
  "good-natured": "de bon caràcter",
  "merry": "joiós",
  "optimistic": "optimista",
  "sensitive": "sensible",
  "sweet-tempered": "de caràcter dolç",
  "tenacious": "tenaç",
  "variable depending on ancestry and individual traits": "variable segons l'ascendència i els trets individuals",
};
