// GENERAT AUTOMÀTICAMENT des de docs/exercicis — no editar a mà.
// Torna a generar-ho amb: npm run exercicis:genera

import type { BlocInfo, Exercise } from '@vincle/shared-types';

/** Noms i descripcions dels cinc blocs del catàleg. */
export const BLOCS_CATALEG: readonly { bloc: number; nom: string; descripcio: string }[] = [
  { bloc: 1, nom: "Base", descripcio: "<!-- Descripció del bloc 1 -->" },
  { bloc: 2, nom: "Ordres", descripcio: "<!-- Descripció del bloc 2 -->" },
  { bloc: 3, nom: "Carrer", descripcio: "<!-- Descripció del bloc 3 -->" },
  { bloc: 4, nom: "Entrenament", descripcio: "<!-- Descripció del bloc 4 -->" },
  { bloc: 5, nom: "Carícies", descripcio: "<!-- Descripció del bloc 5 -->" },
];

/** Catàleg curat d'exercicis. Contingut de referència: l'app no en crea de nous.
 *  Escrit per la responsable del projecte com a part del marc pràctic del TR. */
export const EXERCICIS: readonly Exercise[] = [
  {
    id: "e1-1",
    bloc: 1,
    ordre: 1,
    nom: "Clicker",
    explicacio: "«Carregar el clicker» és una activitat senzilla. Activarem el clicker i\nimmediatament després li donarem al nostre gos un premi que li agradi. Així\nsuccessivament fins que entengui que el «clic» va associat amb el menjar.",
    nota: "El clicker pot ser substituït per paraules (com ara «Bé!»), carícies o jocs.",
    recomanacio: { tipus: "pauta", sessionsMin: 3, sessionsMax: 4, frequencia: "diaria", dies: 6, minutsPerSessio: null },
    milestoneIds: [],
  },
  {
    id: "e1-2",
    bloc: 1,
    ordre: 2,
    nom: "No mossegar",
    explicacio: "Important practicar-ho abans dels 4 o 5 mesos d’edat. \nQuan juguem a mossegar, el cadell encara no sabrà regular la força de les seves dents, i podem aprofitar-ho per ensenyar-li. \n\nSi mossega i fa mal, diem “No” immediatament, i després obrirem amb compte la seva boca amb l’altra mà i pararem el joc durant uns segons. Així el cadell entendrà que no t’ha agradat i que mossegar així para el joc, cosa que ell no voldrà, i mirarà de regular-se.\n\nNota: Recorda d’obrir-li la boca al cadell, estirant la mà et podria esgarrapar.",
    nota: "IMPORTANT! Per molt que ens faci mal, MAI castigar físicament el gos!",
    recomanacio: { tipus: "lliure", text: "No es recomana cap nombre concret de sessions, aquesta mesura es va aprenent fins que el cadell canvia les dents" },
    milestoneIds: [],
  },
  {
    id: "e1-3",
    bloc: 1,
    ordre: 3,
    nom: "Socialitzar",
    explicacio: "Hem d’acostumar el cadell als llocs que freqüentarà quan sigui gran. A partir dels quatre mesos, els gossos solen tornar-se més cautelosos i reben negativament els llocs nous. \n\nUn gos preparat per intervencions hauria d’estar acostumat a aquests llocs:\n- Parc (nens i altres gossos)\n- Cotxe\n- Ciutat\n- Persones amb bastó\n- Boscos\n- Ascensors\n- Transport públic\n- Platja\n- Veus altes\n- Bicicletes\n- Hospital\n- Crosses\n- Cadires de rodes\n- Escoles\n- Comportament inesperat",
    nota: "És important mantenir-ho al llarg de la vida, per què el gos adult no oblidi els llocs que va visitar de petit.",
    recomanacio: { tipus: "pauta", sessionsMin: 1, sessionsMax: 1, frequencia: "diaria", dies: null, minutsPerSessio: null },
    milestoneIds: [],
  },
  {
    id: "e2-1",
    bloc: 2,
    ordre: 1,
    nom: "Seu",
    explicacio: "Sabies que els gossos poden mirar amunt més còmodament quan estan assentats? Per aquest exercici, utilitzarem el luring, amb el premi davant seu i l’anirem movent cap amunt. Quan segui, li donem el premi. \n\nAl cap d’uns intents, haurà entès que ha de seure per aconseguir el premi, i llavors introduirem l’ordre “Seu” just abans d’acostar la mà cap al gos.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 2, sessionsMax: 2, frequencia: "diaria", dies: 3, minutsPerSessio: 10 },
    milestoneIds: [],
  },
  {
    id: "e2-2",
    bloc: 2,
    ordre: 2,
    nom: "A terra",
    explicacio: "Un cop el cadell sap seure quan li demanem, podem passar a fer-lo estirar-se. Per això, el farem seure i, amb luring, baixarem el premi cap avall, seguint el tors del gos. Com que li serà incòmode, jaurà, i llavors li donarem el premi. Un cop ho entengui, direm “A terra” just abans de baixar la mà.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 3, sessionsMax: 3, frequencia: "diaria", dies: 4, minutsPerSessio: 10 },
    milestoneIds: [],
  },
  {
    id: "e2-3",
    bloc: 2,
    ordre: 3,
    nom: "Quiet",
    explicacio: "Amb la corretja lligada, li demanarem al gos que segui. Li posarem un premi davant del morro i farem mitja volta al voltant del gos. Si es queda quiet, el premiem. Després podem anar augmentant la distància:\n- Una volta sencera\n- Una volta a més distància\n- Anar enrere en línia recta\n- Anar més lluny\n- Amagar-se\n- Tirar la pilota",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 2, sessionsMax: 2, frequencia: "total", dies: 2, minutsPerSessio: 15 },
    milestoneIds: [],
  },
  {
    id: "e2-4",
    bloc: 2,
    ordre: 4,
    nom: "Vine",
    explicacio: "Necessitarem una corda llarga o una corretja extensible.\n\nEns col·loquem al seu costat i li donem un premi (o utilitzem el clicker) just després de dir “Vine”. Després d’algunes repeticions, podem començar a allunyar-nos: primer una passa i anem fent a poc a poc.",
    nota: "Si no entén el que ha de fer quan ens allunyem, podem ajudar-nos de la corda per acostar-lo.",
    recomanacio: { tipus: "pauta", sessionsMin: 5, sessionsMax: 5, frequencia: "total", dies: 5, minutsPerSessio: 20 },
    milestoneIds: [],
  },
  {
    id: "e2-5",
    bloc: 2,
    ordre: 5,
    nom: "Agafar / donar",
    explicacio: "Per aquest exercici necessitarem dues joguines iguals, perquè el gos no perdi l’interès. N’aguantarem una a cada mà, i jugarem només amb una. La pararem i començarem a sacsejar l’altra. El gos la deixarà i agafarà la nova joguina. Ho anirem repetint, i quan parem una joguina direm “Deixa”.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 5, sessionsMax: 5, frequencia: "total", dies: 5, minutsPerSessio: 20 },
    milestoneIds: [],
  },
  {
    id: "e3-1",
    bloc: 3,
    ordre: 1,
    nom: "Caminar tranquil",
    explicacio: "Aquest exercici és molt semblant a la ordre “Vine”. Col·locarem un premi al costat del nostre cos i direm “Junts”, perquè no confongui les dues ordres. Farem un pas i li donarem el premi.\n\nUn cop n’haguem fet uns quants, canviarem el premi de mà per què vegi que ens ha de seguir a nosaltres i no la mà. Llavors començarem a fer  dos i més passos, corbes i voltes.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 1, sessionsMax: 1, frequencia: "diaria", dies: 15, minutsPerSessio: 15 },
    milestoneIds: [],
  },
  {
    id: "e3-2",
    bloc: 3,
    ordre: 2,
    nom: "Altres gossos",
    explicacio: "Per aprendre a tolerar els altres gossos i no jugar-hi, podem premiar-los sempre que no estiri cap al gos. \n\nPels cadells, podem agafar una manta i seure prop d’un parc on passin gossos sovint. Així, quan vegi gossos però no s’hi vulgui acostar, el premiarem amb el clicker o menjar. \n\nSi el gos ja va a passeig, ho aprofitarem per seguir el mateix sistema. Començarem allunyats dels gossos i mica en mica ens hi aproparem més.\n\nAnirem baixant gradualment la ràtio de premis.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 21, sessionsMax: 21, frequencia: "total", dies: 21, minutsPerSessio: null },
    milestoneIds: [],
  },
  {
    id: "e3-3",
    bloc: 3,
    ordre: 3,
    nom: "Acceptar desconegut",
    explicacio: "Farem seure el gos en algun lloc amb algú de confiança però que ell encara no conegui. Li donarem la corretja a l’altra persona i marxarem. \n\nL’objectiu és que no cridi, plori o intenti fugar-se. Mentre es mantingui tranquil i assentat, el “desconegut” li anirà donant premis. Al cap d’uns minuts, tornarem amb el gos i llavors tornarem a marxar.",
    nota: "Recomanació: 8 sessions d’uns 20 minuts, amb 8 persones diferents.",
    recomanacio: { tipus: "pauta", sessionsMin: 8, sessionsMax: 8, frequencia: "total", dies: 8, minutsPerSessio: 20 },
    milestoneIds: [],
  },
  {
    id: "e3-4",
    bloc: 3,
    ordre: 4,
    nom: "Xoc per darrere",
    explicacio: "Li demanarem al gos que es quedi quiet, i una segona persona xocarà amb ell per darrere. Pot reaccionar, però no excessivament. Si no crida, salta o ronca, li donarem un premi o activarem el clicker.",
    nota: "Recomanació: 8 sessions d’uns 10 minuts, amb 8 persones diferents.",
    recomanacio: { tipus: "pauta", sessionsMin: 8, sessionsMax: 8, frequencia: "total", dies: 8, minutsPerSessio: 10 },
    milestoneIds: [],
  },
  {
    id: "e4-1",
    bloc: 4,
    ordre: 1,
    nom: "Distraccions",
    explicacio: "Nosaltres acariciarem el gos mentre una segona persona fa altres coses al voltant. Pot tirar coses al terra, estossegar fort, saltar… Nosaltres donarem un premi o el clicker al gos cada vegada que no reaccioni exageradament. \n\nQuan el gos ho entengui, la segona persona començarà a fer soroll fora de la sala, lluny o en espais oberts.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 6, sessionsMax: 6, frequencia: "total", dies: 6, minutsPerSessio: 20 },
    milestoneIds: [],
  },
  {
    id: "e4-2",
    bloc: 4,
    ordre: 2,
    nom: "Gestos exagerats",
    explicacio: "Tindrem una conversa amb una altra persona davant del gos. Farem gestos estranys i grossos, i cada vegada que fem alguna cosa exagerada (com un salt o obrir molt els braços de cop), si el gos no reacciona, li donem un premi o el clicker. \n\nSi reacciona, direm “No” i seguirem amb la conversa.\n\nQuan el gos entengui que ha d’estar calmat, passarem a dirigir-li els gestos a ell i seguir el mateix sistema.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 3, sessionsMax: 3, frequencia: "total", dies: 3, minutsPerSessio: 15 },
    milestoneIds: [],
  },
  {
    id: "e4-3",
    bloc: 4,
    ordre: 3,
    nom: "Crits i ràbia",
    explicacio: "Seguirem el mateix procediment que en l’exercici anterior, però ara canviant la conversa per una discussió. Premiarem al gos quan no reaccioni als crits forts i direm “No” quan reaccioni.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 5, sessionsMax: 5, frequencia: "total", dies: 5, minutsPerSessio: 5 },
    milestoneIds: [],
  },
  {
    id: "e5-1",
    bloc: 5,
    ordre: 1,
    nom: "Acceptar carícies",
    explicacio: "Li demanarem al gos que es quedi quiet mentre una altra persona s’acosta i li fa carícies. Cada gest nou que faci la persona serà un premi o clicker pel gos. Li anirem repetint que es quedi quiet perquè sàpiga el que ha de fer.",
    nota: "Recomanació: 3 sessions de 5 minuts, amb 5 persones diferents.",
    recomanacio: { tipus: "pauta", sessionsMin: 3, sessionsMax: 3, frequencia: "total", dies: 3, minutsPerSessio: 5 },
    milestoneIds: [],
  },
  {
    id: "e5-2",
    bloc: 5,
    ordre: 2,
    nom: "Carícies sapastres",
    explicacio: "En algun moment que li fem carícies normals, canviarem a tocar-lo amb els colzes i els peus, rient i cridant. Donarem un premi al gos quan es quedi quiet i direm “No” quan ronqui o intenti marxar.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 5, sessionsMax: 5, frequencia: "total", dies: 5, minutsPerSessio: 5 },
    milestoneIds: [],
  },
  {
    id: "e5-3",
    bloc: 5,
    ordre: 3,
    nom: "Abraçada restrictiva",
    explicacio: "Si és un gos gran, preferiblement entrenar-lo quan és un cadell. \n\nL’agafarem a coll i li donarem un premi o clicker immediatament. L’anirem agafant en posicions més restrictives, que no es pugui moure, i el premiarem perquè vegi que és bo.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 4, sessionsMax: 4, frequencia: "total", dies: 4, minutsPerSessio: 10 },
    milestoneIds: [],
  },
  {
    id: "e5-4",
    bloc: 5,
    ordre: 4,
    nom: "Moltes carícies",
    explicacio: "Li demanem que jegui a terra mentre dues persones l’acaricien. Li donarem premis de tant en tant.\n\nLlavors passarem a tres persones alhora, quatre i fins i tot cinc, i l’anirem premiant.",
    nota: null,
    recomanacio: { tipus: "pauta", sessionsMin: 3, sessionsMax: 3, frequencia: "total", dies: 3, minutsPerSessio: 10 },
    milestoneIds: [],
  },
];

/** Els exercicis d'un bloc, en ordre. */
export function exercicisDelBloc(bloc: number): readonly Exercise[] {
  return EXERCICIS.filter((e) => e.bloc === bloc);
}

export type { BlocInfo };
